version: '3.5'

services:
  postgres:
    container_name: postgres_container
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-JimBom05@}
      PGDATA: /data/postgres
    volumes:
      - postgresdata:/Users/akifova/Development/db/postgres/data/
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped

#  pgadmin:
#    container_name: pgadmin_container
#    image: dpage/pgadmin4
#    environment:
#      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-akif.ova@gmail.com}
#      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-JimBom05@}
#    volumes:
#      - pgadmin:/root/.pgadmin
#    ports:
#      - "${PGADMIN_PORT:-5050}:80"
#    networks:
#      - postgres
#    restart: unless-stopped
  redis:
    container_name: redis_container
    image: redis:alpine
    ports:
      - "6379:6379"
    command: redis-server --requirepass JimBom05@
    networks:
      - redis
networks:
  postgres:
    driver: bridge
  redis:
    driver: "bridge"
volumes:
  postgresdata:
  #pgadmin:
  #command: bash -c "echo \"host all  all  0.0.0.0/0  md5\" >> /etc/postgresql/9.3/main/pg_hba.conf && echo \"listen_addresses='*'\" >> /etc/postgresql/9.3/main/postgresql.conf"

