spring:
    datasource:
        driverClassName: org.postgresql.Driver
        url: jdbc:postgresql://localhost:5432/derlem_dev?useUnicode=true&characterEncoding=utf8&
        username: username
        password: password
    jpa:
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        database: postgresql
        show-sql: true
        properties:
            hibernate.connection.CharSet: utf8
            hibernate.connection.characterEncoding: utf8
            hibernate.jdbc.lob.non_contextual_creation: true
            org:
                hibernate:
                    envers:
                        audit_table_suffix: _aud
                        default_schema: audit
        hibernate:
            ddl-auto: none
            naming:
              implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl
    thymeleaf:
        cache: false
    session:
        store-type: none
    data:
        mongodb:
            database: carp
debug: false
trace: false
logging:
    level:
        root: error
        org:
            springframework:
                security: error
                web: debug
                data:
                    mongodb:
                        core:
                            MongoTemplate: error
            hibernate:
                SQL: error
                type: error
            apache:
                commons:
                    dbcp2: error
        com:
            zaxxer:
                hikari:
                    pool:
                        HikariPool: error
                        PoolBase: error
                    HikariDataSource: error
derlem:
    server:
        ip-address: http://37.247.105.22
        file:
            path:
                linux: /home/kazu/derlem
                osx: /Users/akifova/derlem
                win: x:\
