Create user kazu WITH PASSWORD 'jT36+Kxse@' CREATEDB;

CREATE DATABASE derlem
    WITH
    OWNER = kazu
    ENCODING = 'UTF8'
    CONNECTION LIMIT = -1;

CREATE SCHEMA audit AUTHORIZATION kazu;
CREATE SCHEMA sec AUTHORIZATION kazu;
CREATE SCHEMA common AUTHORIZATION kazu;
CREATE SCHEMA stock_card AUTHORIZATION kazu;
CREATE SCHEMA design AUTHORIZATION kazu;
CREATE SCHEMA yarn AUTHORIZATION kazu;
CREATE SCHEMA specimen AUTHORIZATION kazu;